### ISSUE TITLE
✨ [chore] GitHub Actions の動作確認で作成する Issue 数を調整

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [Sunwood-ai-labs/Yukihiko#26]
- GitHub Actions の動作確認において、Issue の作成数が多すぎる問題を解消するため、作成する Issue 数を 1 件から 5 件に変更しました。
- これにより、動作確認に必要な Issue 数を確保しつつ、Issue リストが冗長になることを防ぎます。

# info

- コミットSHA: 85c063aba43b5ff37feab523b58e746eb0d177bc
- コミット日時: 2024-07-23 12:21:59+00:00
- コミット作成者: Maki <sunwood.ai.labs@gmail.com>

**Comment by yukihiko-fuyuki** [comment]
## 論文要約

## 論文要約

GitHub Actionsの動作確認を効率化するため、以下の変更を行いました。

* 動作確認時に自動作成されるIssueの数を、従来の1件から**5件に増加**。
* これにより、必要な確認作業は担保しつつ、Issueリストの肥大化を防ぎます。
