### ISSUE TITLE
✨ [feat] PyPIへの自動パブリッシュワークフローを追加

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [Sunwood-ai-labs/Yukihiko#28]
- 新しいGitHub Actionsワークフロー(`.github/workflows_off/publish-to-pypi.yml`)を追加しました。
- このワークフローは、タグがプッシュされた際に、パッケージをPyPIに自動的にパブリッシュします。
- これにより、リリースプロセスが簡素化され、手動でのアップロードが不要になります。

# info

- コミットSHA: de5f4bb79f4c36f5da0b78362155541ec0f97195
- コミット日時: 2024-07-23 11:58:58+00:00
- コミット作成者: Maki <sunwood.ai.labs@gmail.com>

**Comment by yukihiko-fuyuki** [comment]
@yukihiko-fuyuki が以下のラベルを提案し、適用しました：

- GitHub Actions
- 新機能
- PyPI

以下の新しいラベルが作成され、適用されました：

- PyPI

**Comment by yukihiko-fuyuki** [comment]
## 論文要約

## 論文要約

この論文は、PyPIへの自動パブリッシュワークフローの追加について述べています。

- 新しいGitHub Actionsワークフロー `.github/workflows_off/publish-to-pypi.yml` が導入されました。
- このワークフローにより、タグがプッシュされると自動的にパッケージがPyPIにパブリッシュされます。
- 結果として、リリースプロセスが簡素化され、手動アップロードが不要になります。
