### ISSUE TITLE
🔧 [chore] リリースバージョンをv0.1.0に更新

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [Sunwood-ai-labs/Yukihiko#29]
- リリースノート生成の設定ファイルにおいて、バージョンをv0.1.0に修正しました。

# info

- コミットSHA: 10e18786c5c24860f672aa807c9d6a162e8e0ce7
- コミット日時: 2024-07-23 11:55:24+00:00
- コミット作成者: Maki <sunwood.ai.labs@gmail.com>

**Comment by yukihiko-fuyuki** [comment]
## 論文要約

## 論文要約

この論文は、実際には学術論文ではなく、ソフトウェア開発におけるバージョン管理に関する短い技術メモです。

* この変更はソフトウェアのリリースバージョンを `v0.1.0` に更新することを目的としています。
* 具体的には、リリースノートを自動生成するための設定ファイル内のバージョン番号を修正しています。
* つまり、この変更自体はソフトウェアの機能や性能に影響を与えるものではなく、リリース作業の一環として行われたものです。

**Comment by yukihiko-fuyuki** [comment]
@yukihiko-fuyuki が以下のラベルを提案し、適用しました：

- GitHub Actions
- 新機能
