### ISSUE TITLE
✨ [docs] usage.mdを追加

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [Sunwood-ai-labs/Yukihiko#31]
SourceSageの使い方を記述したusage.mdを追加しました。
現状は準備中のため、内容は後日追記予定です。

# info

- コミットSHA: 6b6d0018cb3be0991553afc9eb355132fafc6bf0
- コミット日時: 2024-07-23 11:31:37+00:00
- コミット作成者: Maki <sunwood.ai.labs@gmail.com>

**Comment by yukihiko-fuyuki** [comment]
## 論文要約

## 論文要約

本論文は、arXivに提出されたものではなく、SourceSageというプロジェクトのコミットに関する情報です。

- **変更点:** SourceSageの使い方を記述した `usage.md` ファイルが新規に追加されました。
- **現時点での状態:**  `usage.md` は準備段階であり、具体的な内容は後日追記される予定です。
