### ISSUE TITLE
✨ [feat] リリースノート生成のための設定ファイルを追加

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [Sunwood-ai-labs/Yukihiko#32]
SourceSageを使ってリリースノートを自動生成するための設定ファイルを追加しました。
これにより、バージョン間の変更点を自動的に追跡し、リリースノートの作成プロセスを簡略化できます。

- SourceSageの設定ファイル(.sourcesage_releasenotes.yml)を追加
- リリースノート生成に必要な設定項目を追加

# info

- コミットSHA: cf88138b1dfc0e066d71ca676f9ee2a82eaa6d1f
- コミット日時: 2024-07-23 11:31:34+00:00
- コミット作成者: Maki <sunwood.ai.labs@gmail.com>

**Comment by yukihiko-fuyuki** [comment]
## 論文要約

## 論文要約

この論文は、SourceSageというツールを使ってリリースノートを自動生成するための設定ファイル追加について述べています。

- **新機能:** SourceSageの設定ファイル(.sourcesage_releasenotes.yml)が追加されました。
- **メリット:** この設定ファイルによってバージョン間の変更点が自動で追跡され、リリースノート作成が簡素化されます。
