### ISSUE TITLE
🤖 [chore] PR自動マージの成功率向上

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [Sunwood-ai-labs/Yukihiko#36]
- paper_scraper.ymlのワークフロー内で、プルリクエストURLが正しく取得できない場合に発生していたエラーを修正しました。
- これにより、プルリクエストの自動マージがより安定して実行されます。

# info

- コミットSHA: 48e6525b6b1862fc7885ba71fcad1d9f01f7de97
- コミット日時: 2024-07-22 14:55:12+00:00
- コミット作成者: Maki <sunwood.ai.labs@gmail.com>

**Comment by yukihiko-fuyuki** [comment]
## 論文要約

## 論文要約: 🤖 PR自動マージの成功率向上

この論文は、プルリクエスト（PR）の自動マージ機能の安定性向上に関するものです。

* 従来、PRのURL取得に失敗し、自動マージが正しく動作しないケースがありました。
* 今回の修正により、 `paper_scraper.yml` ワークフローにおけるURL取得処理のエラーが解消されました。
* これにより、PR自動マージがより安定して実行されるようになります。

**Comment by yukihiko-fuyuki** [comment]
@yukihiko-fuyuki が以下のラベルを提案し、適用しました：

- GitHub Actions
- 新機能
- ロボティクス

以下の新しいラベルが作成され、適用されました：

- ロボティクス
